#!/usr/bin/env node

/**
 * Generate TypeScript types from JSON Schema definitions using json-schema-to-typescript
 */

import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { compile } from 'json-schema-to-typescript';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const SCHEMAS_DIR = path.join(__dirname, '../schemas');
const OUTPUT_DIR = path.join(__dirname, '../src/types');
const OUTPUT_FILE = path.join(OUTPUT_DIR, 'schema-types.generated.ts');

// Ensure output directory exists
if (!fs.existsSync(OUTPUT_DIR)) {
  fs.mkdirSync(OUTPUT_DIR, { recursive: true });
}

console.log('🔧 Generating TypeScript types from JSON schemas...');

// Schema files to process (explicit order to avoid duplicate types)
const schemaFiles = ['events.schema.json', 'handshake.schema.json', 'pay-button-params.schema.json'];

let generatedTypes = `/**
 * Generated TypeScript types from JSON schemas
 * 
 * ⚠️  DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated from JSON schemas in the schemas/ directory.
 */

`;

try {
  for (const schemaFile of schemaFiles) {
    const schemaPath = path.join(SCHEMAS_DIR, schemaFile);
    
    if (!fs.existsSync(schemaPath)) {
      console.warn(`⚠️  Schema file not found: ${schemaFile}`);
      continue;
    }

    console.log(`   Processing: ${schemaFile}`);
    
    const schemaContent = fs.readFileSync(schemaPath, 'utf8');
    const schema = JSON.parse(schemaContent);
    
    // НАСТОЯЩАЯ генерация типов из JSON Schema
    const typescript = await compile(schema, schema.title || 'Generated', {
      cwd: SCHEMAS_DIR,
      bannerComment: '',
      style: {
        singleQuote: true,
        semi: true
      },
      additionalProperties: false
    });
    
    generatedTypes += `// Generated from ${schemaFile}\n`;
    generatedTypes += typescript;
    generatedTypes += '\n';
  }

  fs.writeFileSync(OUTPUT_FILE, generatedTypes);
  
  console.log(`✅ Generated types written to: ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  console.log(`📊 Processed ${schemaFiles.length} schema files using json-schema-to-typescript`);
  
} catch (error) {
  console.error('❌ Type generation failed:', error);
  process.exit(1);
}