/**
 * HARDCODED TypeScript types from JSON schemas
 * 
 * ⚠️  DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated from JSON schemas in the schemas/ directory.
 */

// Generated from instant-pay-config.schema.json
/**
 * TON network identifier
 */
export type Network = 'mainnet' | 'testnet';
/**
 * Button label for payment action
 */
export type PayLabel = 'buy' | 'unlock' | 'use' | 'get' | 'open' | 'start' | 'retry' | 'show' | 'play' | 'try';

/**
 * Configuration object containing wallet limits, network info, and available options
 */
export interface Config {
  network: Network;
  /**
   * Maximum TON amount for instant payments (decimal string)
   */
  tonLimit: string;
  /**
   * List of supported jettons with their limits
   */
  jettons: {
    /**
     * Human-readable jetton symbol (e.g., 'USDT')
     */
    symbol: string;
    /**
     * Jetton master contract address
     */
    address: string;
    /**
     * Number of decimal places for the jetton
     */
    decimals: number;
    /**
     * Maximum jetton amount for instant payments (decimal string)
     */
    limit: string;
  }[];
  /**
   * Available button labels for payment actions
   */
  labels: PayLabel[];
}

// Generated from ip-event.schema.json
/**
 * Union type for all InstantPay events emitted by the wallet
 */
export type Event = ClickEvent | SentEvent | CancelledEvent;

/**
 * Emitted when user clicks the pay button
 */
export interface ClickEvent {
  type: 'click';
  /**
   * UUID of the invoice being processed
   */
  invoiceId: string;
}
/**
 * Emitted when transaction is successfully broadcast to the network
 */
export interface SentEvent {
  type: 'sent';
  /**
   * UUID of the completed invoice
   */
  invoiceId: string;
  /**
   * Base64-encoded BOC of the sent transaction
   */
  boc: string;
}
/**
 * Emitted when user cancels the payment or an error occurs
 */
export interface CancelledEvent {
  type: 'cancelled';
  /**
   * UUID of the cancelled invoice
   */
  invoiceId: string;
}

// Generated from set-pay-button-params.schema.json
/**
 * Parameters for rendering or updating the InstantPay button
 */
export interface SetPayButtonParams {
  /**
   * Payment amount as decimal string, includes network fee
   */
  amount: string;
  /**
   * Bounceable TON address of the payment recipient
   */
  recipient: string;
  /**
   * Button label indicating the payment action
   */
  label: PayLabel;
  /**
   * Unique UUID identifying this payment invoice
   */
  invoiceId: string;
  /**
   * Optional jetton master contract address for jetton payments
   */
  jetton?: string;
  /**
   * Optional merchant ADNL address for enhanced security
   */
  adnlAddress?: string;
}

