/**
 * Generated TypeScript types from JSON schemas
 * 
 * ⚠️  DO NOT EDIT THIS FILE DIRECTLY
 * This file is auto-generated from JSON schemas in the schemas/ directory.
 */

// Generated from events.schema.json
export type InstantPayEvent =
  | {
      type: 'ready';
      handshake: {
        protocolVersion: string;
        wallet: {
          name: string;
        };
      };
    }
  | {
      type: 'click';
      invoiceId: string;
    }
  | {
      type: 'sent';
      invoiceId: string;
      boc: string;
    }
  | {
      type: 'cancelled';
      invoiceId: string;
      reason?: 'user' | 'app' | 'wallet' | 'replaced' | 'expired' | 'unsupported_env';
    }
  | {
      type: 'handoff';
      invoiceId: string;
      url: string;
      scheme: 'ton' | 'https';
    };

// Generated from pay-button-params.schema.json
export interface PayButtonParams {
  request: PaymentRequest;
  label: 'buy' | 'unlock' | 'use' | 'get' | 'open' | 'start' | 'retry' | 'show' | 'play' | 'try';
  instantPay?: boolean;
}
export interface PaymentRequest {
  amount: string;
  recipient: string;
  invoiceId: string;
  asset:
    | {
        type: 'ton';
      }
    | {
        type: 'jetton';
        master: string;
      };
  adnlAddress?: string;
  expiresAt?: number;
}

